"""Handler registry for mapping services to handlers."""

from typing import Dict, Type
from .base_handler import ResourceHandler
from .handlers import (
    # Existing handlers
    EC2Handler,
    S3Handler,
    RDSHandler,
    LambdaHandler,
    IAMHandler,
    DynamoDBHandler,
    CloudFormationHandler,
    ECSHandler,
    SNSHandler,
    SQSHandler,
    CloudWatchHandler,
    APIGatewayHandler,
    ELBHandler,
    Route53Handler,
    VPCHandler,
    ECRHandler,
    EKSHandler,
    KinesisHandler,
    AthenaHandler,
    GlueHandler,
    RedshiftHandler,
    ElastiCacheHandler,
    KMSHandler,
    SecretsManagerHandler,
    GuardDutyHandler,
    # New handlers
    AcmHandler,
    AppflowHandler,
    AppmeshHandler,
    ApprunnerHandler,
    AppstreamHandler,
    AutoscalingHandler,
    BackupHandler,
    BatchHandler,
    ChimeHandler,
    Cloud9Handler,
    CloudfrontHandler,
    CloudhsmHandler,
    CloudmapHandler,
    CloudsearchHandler,
    CloudtrailHandler,
    CodeartifactHandler,
    CodebuildHandler,
    CodecommitHandler,
    CodedeployHandler,
    CodepipelineHandler,
    CognitoHandler,
    ComprehendHandler,
    ConfigHandler,
    ConnectHandler,
    DatasyncHandler,
    DetectiveHandler,
    DirectconnectHandler,
    DmsHandler,
    DocdbHandler,
    EfsHandler,
    ElasticbeanstalkHandler,
    ElastictranscoderHandler,
    EmrHandler,
    EventbridgeHandler,
    FirehoseHandler,
    FmsHandler,
    ForecastHandler,
    FrauddetectorHandler,
    FsxHandler,
    GlacierHandler,
    GlobalacceleratorHandler,
    ImagebuilderHandler,
    InspectorHandler,
    IotHandler,
    IotanalyticsHandler,
    IoteventsHandler,
    IotsitewiseHandler,
    IvsHandler,
    KafkaHandler,
    KendraHandler,
    KeyspacesHandler,
    LakeformationHandler,
    LightsailHandler,
    MacieHandler,
    MediaconvertHandler,
    MedialiveHandler,
    MediapackageHandler,
    MediastoreHandler,
    MediatailorHandler,
    MemorydbHandler,
    MqHandler,
    NeptuneHandler,
    OpensearchHandler,
    OpsworksHandler,
    OrganizationsHandler,
    OutpostsHandler,
    PersonalizeHandler,
    PinpointHandler,
    PollyHandler,
    QldbHandler,
    QuicksightHandler,
    RamHandler,
    RekognitionHandler,
    SagemakerHandler,
    SecurityhubHandler,
    ServerlessrepoHandler,
    ServicecatalogHandler,
    SesHandler,
    ShieldHandler,
    SignerHandler,
    SsmHandler,
    StepfunctionsHandler,
    StoragegatewayHandler,
    StsHandler,
    SwfHandler,
    TextractHandler,
    TimestreamHandler,
    TranscribeHandler,
    TransferHandler,
    TranslateHandler,
    WafHandler,
    Wafv2Handler,
    WorkdocsHandler,
    WorkmailHandler,
    WorkspacesHandler,
    XrayHandler,
)


# Service name to handler class mapping
HANDLER_REGISTRY: Dict[str, Type[ResourceHandler]] = {
    # Existing handlers
    "ec2": EC2Handler,
    "s3": S3Handler,
    "rds": RDSHandler,
    "lambda": LambdaHandler,
    "iam": IAMHandler,
    "dynamodb": DynamoDBHandler,
    "cloudformation": CloudFormationHandler,
    "ecs": ECSHandler,
    "sns": SNSHandler,
    "sqs": SQSHandler,
    "cloudwatch": CloudWatchHandler,
    "logs": CloudWatchHandler,  # CloudWatch Logs uses same handler
    "apigateway": APIGatewayHandler,
    "apigatewayv2": APIGatewayHandler,  # API Gateway v2 uses same handler
    "elb": ELBHandler,
    "elbv2": ELBHandler,  # ELBv2 uses same handler
    "route53": Route53Handler,
    "vpc": VPCHandler,
    "ecr": ECRHandler,
    "eks": EKSHandler,
    "kinesis": KinesisHandler,
    "athena": AthenaHandler,
    "glue": GlueHandler,
    "redshift": RedshiftHandler,
    "elasticache": ElastiCacheHandler,
    "kms": KMSHandler,
    "secretsmanager": SecretsManagerHandler,
    "guardduty": GuardDutyHandler,
    # New handlers
    "acm": AcmHandler,
    "appflow": AppflowHandler,
    "appmesh": AppmeshHandler,
    "apprunner": ApprunnerHandler,
    "appstream": AppstreamHandler,
    "autoscaling": AutoscalingHandler,
    "backup": BackupHandler,
    "batch": BatchHandler,
    "chime": ChimeHandler,
    "cloud9": Cloud9Handler,
    "cloudfront": CloudfrontHandler,
    "cloudhsm": CloudhsmHandler,
    "cloudmap": CloudmapHandler,
    "cloudsearch": CloudsearchHandler,
    "cloudtrail": CloudtrailHandler,
    "codeartifact": CodeartifactHandler,
    "codebuild": CodebuildHandler,
    "codecommit": CodecommitHandler,
    "codedeploy": CodedeployHandler,
    "codepipeline": CodepipelineHandler,
    "cognito": CognitoHandler,
    "comprehend": ComprehendHandler,
    "config": ConfigHandler,
    "connect": ConnectHandler,
    "datasync": DatasyncHandler,
    "detective": DetectiveHandler,
    "directconnect": DirectconnectHandler,
    "dms": DmsHandler,
    "docdb": DocdbHandler,
    "efs": EfsHandler,
    "elasticbeanstalk": ElasticbeanstalkHandler,
    "elastictranscoder": ElastictranscoderHandler,
    "emr": EmrHandler,
    "eventbridge": EventbridgeHandler,
    "firehose": FirehoseHandler,
    "fms": FmsHandler,
    "forecast": ForecastHandler,
    "frauddetector": FrauddetectorHandler,
    "fsx": FsxHandler,
    "glacier": GlacierHandler,
    "globalaccelerator": GlobalacceleratorHandler,
    "imagebuilder": ImagebuilderHandler,
    "inspector": InspectorHandler,
    "iot": IotHandler,
    "iotanalytics": IotanalyticsHandler,
    "iotevents": IoteventsHandler,
    "iotsitewise": IotsitewiseHandler,
    "ivs": IvsHandler,
    "kafka": KafkaHandler,
    "kendra": KendraHandler,
    "keyspaces": KeyspacesHandler,
    "lakeformation": LakeformationHandler,
    "lightsail": LightsailHandler,
    "macie": MacieHandler,
    "mediaconvert": MediaconvertHandler,
    "medialive": MedialiveHandler,
    "mediapackage": MediapackageHandler,
    "mediastore": MediastoreHandler,
    "mediatailor": MediatailorHandler,
    "memorydb": MemorydbHandler,
    "mq": MqHandler,
    "neptune": NeptuneHandler,
    "opensearch": OpensearchHandler,
    "opsworks": OpsworksHandler,
    "organizations": OrganizationsHandler,
    "outposts": OutpostsHandler,
    "personalize": PersonalizeHandler,
    "pinpoint": PinpointHandler,
    "polly": PollyHandler,
    "qldb": QldbHandler,
    "quicksight": QuicksightHandler,
    "ram": RamHandler,
    "rekognition": RekognitionHandler,
    "sagemaker": SagemakerHandler,
    "securityhub": SecurityhubHandler,
    "serverlessrepo": ServerlessrepoHandler,
    "servicecatalog": ServicecatalogHandler,
    "ses": SesHandler,
    "shield": ShieldHandler,
    "signer": SignerHandler,
    "ssm": SsmHandler,
    "stepfunctions": StepfunctionsHandler,
    "storagegateway": StoragegatewayHandler,
    "sts": StsHandler,
    "swf": SwfHandler,
    "textract": TextractHandler,
    "timestream": TimestreamHandler,
    "transcribe": TranscribeHandler,
    "transfer": TransferHandler,
    "translate": TranslateHandler,
    "waf": WafHandler,
    "wafv2": Wafv2Handler,
    "workdocs": WorkdocsHandler,
    "workmail": WorkmailHandler,
    "workspaces": WorkspacesHandler,
    "xray": XrayHandler,
}


def get_handler(
    service_name: str,
    region: str,
    dry_run: bool = False,
    force: bool = False,
) -> ResourceHandler:
    """
    Get handler instance for a service.

    Args:
        service_name: AWS service name
        region: AWS region
        dry_run: Dry run mode
        force: Force deletion mode

    Returns:
        Handler instance

    Raises:
        ValueError: If service handler not found
    """
    handler_class = HANDLER_REGISTRY.get(service_name.lower())
    if handler_class is None:
        raise ValueError(f"No handler found for service: {service_name}")

    return handler_class(region=region, dry_run=dry_run, force=force)


def get_available_services() -> list:
    """Get list of available service names."""
    return sorted(set(HANDLER_REGISTRY.keys()))
